---
- name: Set question and answer
  ansible.builtin.set_fact:
    question_name: "Join Wifi"
    WPA_Name: BallsBirds
    flag_token: unhappily

- name: Set MySQL statements
  ansible.builtin.set_fact:
    challenge: INSERT INTO challenges (name, description, max_attempts, value, category, type, state, requirements, connection_info, next_id) VALUES ("{{ question_name }}", "SSH to 192.168.64.17X where X is your user number with '{{ ScrUser }}:password'{{NL2}}Join wlan0 to {{ WPA_Name }}", 0, 5, "Wifi", "standard", "visible", NULL, NULL, NULL)
    answer_flag: INSERT INTO flags (challenge_id, type, content, data) VALUES ((SELECT id FROM challenges WHERE name = "{{ question_name }}"), "static", "{{ flag_token }}", "case_insensitive")

- name: Put challenge into CTFd - Wifi - Join Wifi
  community.mysql.mysql_query:
    query: "{{ challenge }}"

- name: Put flag into CTFd - Wifi - Join Wifi
  community.mysql.mysql_query:
    query: "{{ answer_flag }}"