---
- name: Copy docker-compose to host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /root/

- name: Docker-compose up - Shell
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: /root/

- name: Sleep for 30 seconds to allow Dockers to come up
  ansible.builtin.wait_for:
    timeout: 30

- name: Sleep for 30 seconds to allow CTFd to populate MySql
  ansible.builtin.wait_for:
    timeout: 30