---
- name: Install Docker required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip

- name: Add docker gpg apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    filename: docker
    state: present

- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io

# NEED TO PUT IN A CHECK FOR DOCKER-COMPOSE
- name: Get stats of a file
  ansible.builtin.stat:
    path: /usr/local/bin/docker-compose
  register: file_stats

- name: Install docker-compose - Shell
  ansible.builtin.shell: |
    curl -L https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  when: not file_stats.stat.exists


