---
- name: Run the equivalent of "apt update"
  apt:
    update_cache: yes

- name: Upgrade all packages to their latest version
  apt:
    upgrade: yes

# Installing packages
- name: Install quality of life packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ InitialPackages }}"