---
- name: Run the equivalent of "apt update"
  apt:
    update_cache: yes

- name: Remove apt lock-frontend file
  file:
    state: absent
    path: "/var/lib/dpkg/lock-frontend"

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to their latest version
  apt:
    upgrade: yes

# Installing packages
- name: Install quality of life packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ InitialPackages }}"

- name: Creates directory /mysql_storage for CTFd
  file:
    path: /mysql_storage
    state: directory
    mode: "0777"

- name: Creates directory /ctf_logs for CTFd
  file:
    path: /ctf_logs
    state: directory
    mode: "0777"

- name: Creates directory /ctf_uploads for CTFd
  file:
    path: /ctf_uploads
    state: directory
    mode: "0777"

- name: Creates directory /ctf_uploads for CTFd
  file:
    path: /ctf_uploads/packettracer
    state: directory
    mode: "0777"