# vlc -vvv example.mp4 --sout '#standard{access=http,mux=ts,dst=:8081}'
---
- name: Add the user 'vlc-user'
  ansible.builtin.user:
    name: vlc-user
    shell: /bin/bash
    comment: Purely to run vlc, as it hates root

- name: Copy vlc.sh then make executable
  ansible.builtin.copy:
    src: vlc.sh
    dest: /home/vlc-user/vlc.sh
    mode: '0645'

- name: Copy stream.mp4
  ansible.builtin.copy:
    src: stream.mp4
    dest: /home/vlc-user/stream.mp4
    mode: '0644'

- name: Copy VLCStream service
  ansible.builtin.copy:
    src: vlcstream.service
    dest: /etc/systemd/system/vlcstream.service
    mode: '0644'

- name: Enable vlcstream service
  ansible.builtin.service:
    name: vlcstream
    enabled: true

# Tried with module.. hung forever
- name: Start vlcstream service - Shell
  ansible.builtin.shell: systemctl start vlcstream &