DynamicPassword: $6$jzAOyktnzuCVMtdp$vp4Ne.Z.nKQaipzanj1R.Cvene6xTOQ5mv4sF.nGvtOjSGh4jTJS9pRsLhbRBJYBXRDSUvY.OrHn0Q.kSPVD/. # hambones


InitialPackages:
  - vlc
  - net-tools
  - vim
  - python3-pip

Sudoers:
  - /usr/bin/tcpdump

PipInstalls:
  - pysmb