---
# Setting up the attacker container
# Useful guide for forwarding interfaces: https://blog.simos.info/using-the-lxd-kali-container-image/

- name: Initialise lxd - Shell
  ansible.builtin.shell: lxd init --auto

# To list images
# lxc list images
# lxc image list

# To list running
# lxc list

# To remove
# lxc delete attacker --force

- name: Launch attacker machine - Shell
  ansible.builtin.shell: lxc launch images:alpine/3.14/amd64 attacker

- name: Set autoboot on attacker to true - Shell
  ansible.builtin.shell: lxc config set attacker boot.autostart true
  
# Do some updating on the container and set up ssh server on the container
# Drop into a shell into the container, commands following will be run in the container until we exit it

- name: Container Command - update - Shell
  ansible.builtin.shell: lxc exec attacker -- apk update

- name: Container Command - upgrade - Shell
  ansible.builtin.shell: lxc exec attacker -- apk upgrade

- name: Container Command - install aircrack-ng, openssh - Shell
  ansible.builtin.shell: lxc exec attacker -- apk add iw aircrack-ng openssh pciutils

- name: Container Command - Allow root login - Shell
  ansible.builtin.shell: lxc exec attacker -- ash -c 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config'

- name: Container Command - Allow SSH - Shell
  ansible.builtin.shell: lxc exec attacker -- rc-update add sshd

- name: Container Command - Restart SSH - Shell
  ansible.builtin.shell: lxc exec attacker -- /etc/init.d/sshd start

- name: Container Command - Change root password - Shell
  ansible.builtin.shell: lxc exec attacker -- ash -c 'echo "root:bob" | chpasswd'

- name: Proxy SSH - Shell
  ansible.builtin.shell: lxc config device add attacker sshproxy proxy listen=tcp:0.0.0.0:2222 connect=tcp:127.0.0.1:22
  


# Remove the default bridge device (internet/network access)
- name: Remove the default bridge device - Shell
  ansible.builtin.shell: lxc config device add attacker eth0 none

# Add the bridge device back
- name: Add the bridge device back - Shell
  ansible.builtin.shell: lxc config device remove attacker eth0


# Set up wireless networking on the container
- name: Set up wireless networking on the container - Shell
  ansible.builtin.shell: lxc config device add attacker wifi nic nictype=physical parent=wlan0 name=wlan0
