---
# This is a terrible way to do this, fix this ASAP

# Output hostapd config file
- include_tasks: wpa.yml
- include_tasks: wep.yml

- name: Copy ap_setup.sh then make executable
  ansible.builtin.copy:
    src: ap_setup.sh
    dest: /root/ap_setup.sh
    mode: '0645'

- name: Copy client_loop.sh then make executable
  ansible.builtin.copy:
    src: client_loop.sh
    dest: /root/client_loop.sh
    mode: '0645'

- name: Copy autostart.sh then make executable
  ansible.builtin.copy:
    src: autostart.sh
    dest: /root/autostart.sh
    mode: '0645'

- name: Copy virtual-wifi service
  ansible.builtin.copy:
    src: virtual-wifi.service
    dest: /etc/systemd/system/virtual-wifi.service
    mode: '0644'

- name: Enable virtual-wifi service
  ansible.builtin.service:
    name: virtual-wifi
    enabled: true

- name: Rebooting
  ansible.builtin.reboot:

# Set MAC to random vendor
- name: Set WLAN interface MAC to random vendor - Doesn't persist reboot
  ansible.builtin.shell: macchanger -A wlan{{ item }}
  with_sequence: start=0 end={{ AmountOfInterfaces - 1 }}
  ignore_errors: true