# Disable the default wpa_supplicant service, we'll be starting a client ourselves
- name: Stop service wpa_supplicant, if started
  ansible.builtin.service:
    name: wpa_supplicant
    state: stopped

- name: Disable wpa_supplicant service
  ansible.builtin.service:
    name: wpa_supplicant
    enabled: false

# Create the network interfaces
- name: Create the network interfaces - Shell
  ansible.builtin.shell: modprobe mac80211_hwsim radios=3

# Set up the module to be loaded on boot
- name: Add a line to set up the module to be loaded on boot 1/2
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/vwifi.conf
    line: mac80211_hwsim
    create: yes

- name: Add a line to set up the module to be loaded on boot 2/2
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vwifi.conf
    line: options mac80211_hwsim radios=3
    create: yes

# Assign a static IP to the card, not really used since there's no traffic but could be in the future
- name: Assign a static IP to the wlan1, not really used since there's no traffic - Shell
  ansible.builtin.shell: ip addr add 192.168.21.1/24 dev wlan1 
  ignore_errors: true

