---
- name: Run the equivalent of "apt update"
  apt:
    update_cache: yes

- name: Upgrade all packages to their latest version
  apt:
    upgrade: yes

# Installing packages
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ InitialPackages }}"

# Set fact to change Default Wifi_1 name
- name: Pick {{ AmountOfAPs | int }} random Access Point names
  set_fact:
    APNames: "{{ APNames + [AP_Names | random] }}"
  with_sequence: start=1 end={{ AmountOfAPs | int }}