---
- name: Remove apt lock-frontend file
  file:
    state: absent
    path: "/var/lib/dpkg/lock-frontend"

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Update then Upgrade all packages to their latest version
  apt:
    update_cache: true
    upgrade: yes

# Installing packages
- name: Install quality of life packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ InitialPackages }}"

- name: Add the user scr 
  ansible.builtin.user:
    name: "{{ ScrUser }}"
    password: "{{ ScrPass }}"
    shell: /bin/bash
    comment: Get good

- name: Edit /etc/ssh/sshd_config to allow scr group to SSH - Shell
  ansible.builtin.shell:
    cmd: echo "AllowUsers {{ ScrUser }} ansible" >> /etc/ssh/sshd_config

- name: Restart service ssh, in all cases
  ansible.builtin.service:
    name: ssh
    state: restarted