version: '3'
services:
 db:
   image: mysql:5.7
   restart: always
   ports:
    - "3306:3306"
    - "33060:33060"
   environment:
    - MYSQL_ROOT_PASSWORD=ctfd
    - MYSQL_USER=ctfd
    - MYSQL_PASSWORD=ctfd
    - MYSQL_DATABASE=ctfd
   volumes:
    - /mysql_storage:/var/lib/mysql
 ctfd:
   image: ctfd/ctfd
   user: root
   restart: always
   ports:
    - "8080:8000"
   environment:
    - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
   volumes:
    - /ctf_logs:/opt/CTFd/CTFd/logs
    - /ctf_uploads:/opt/CTFd/CTFd/uploads
   depends_on:
    - db
volumes:
 mysql_storage:
 ctf_logs:
 ctf_uploads: