---
- name: Set question and answer
  ansible.builtin.set_fact:
    question_name: "PacketTracer Lab"
    file_name: lab04-nterVLAN.pka
    flag_token: Marsupialia

- name: Put PacketTracer file onto CTFd
  ansible.builtin.copy:
    src: ../../../PacketTracer/{{ file_name }}
    dest: /ctf_uploads/packettracer/{{ file_name }}
    mode: '0777'

- name: Set MySQL statements
  ansible.builtin.set_fact:
    challenge: INSERT INTO challenges (name, description, max_attempts, value, category, type, state, requirements, connection_info, next_id) VALUES ("{{ question_name }}", "Please work through the attached Packet Tracer lab", 0, 5, "Networking", "standard", "visible", NULL, NULL, NULL)
    answer_flag: INSERT INTO flags (challenge_id, type, content, data) VALUES ((SELECT id FROM challenges WHERE name = "{{ question_name }}"), "static", "{{ flag_token }}", "case_insensitive")
    insert_file: INSERT INTO files (type, location, challenge_id) VALUES ("challenge", "packettracer/{{ file_name }}", (SELECT id FROM challenges WHERE name = "{{ question_name }}"))

- name: Put challenge into CTFd - PacketTracer1
  community.docker.docker_container_exec:
    container: root-db-1
    argv:
      - /bin/bash
      - "-c"
      - "mysql -u ctfd -pctfd -D ctfd -e '{{ challenge }};'"

- name: Put flag into CTFd - PacketTracer1
  community.docker.docker_container_exec:
    container: root-db-1
    argv:
      - /bin/bash
      - "-c"
      - "mysql -u ctfd -pctfd -D ctfd -e '{{ answer_flag }};'"

- name: Put file into CTFd - PacketTracer1
  community.docker.docker_container_exec:
    container: root-db-1
    argv:
      - /bin/bash
      - "-c"
      - "mysql -u ctfd -pctfd -D ctfd -e '{{ insert_file }};'"