---
# 0-19: Users
# 20-29: APs
# 30-39: Fake Users for APs
AmountOfUsers: 20
AmountOfInterfaces: "{{ AmountOfUsers * 2 }}"
AmountOfAPs: "{{ (AmountOfInterfaces - AmountOfUsers) / 2 }}" # 50/50 AP/Clients hence /2
AmountOfClients: "{{ AmountOfAPs }}"

APNames: []

InitialPackages:
  - wpasupplicant
  - hostapd
  - aircrack-ng 
  - wireless-tools
  - net-tools
  
ApkPackages:
  - iw
  - aircrack-ng
  - openssh
  - pciutils

AP_Names:
 - AbhorrentActivity
 - AcquireAction
 - AdaptEarth
 - AfricaAlpha
 - AlfredSecond
 - AmusementApparatus
 - ApproveAddition
 - AssureAunt
 - BallsBirds
 - BeanFiction
 - BelligerentUse
 - BorisBruce
 - BrassCook
 - CadetChief
 - CakesCake
 - CalculateMind
 - ClaraAddress
 - CompactCrater
 - ConcertChant
 - ConfuseMind
 - ConvertHorizon
 - CoverPaper
 - CowboyConcert
 - CrownLanguage
 - DisgustedMetal
 - DolphinCenter
 - EdgeCamera
 - EditedEar
 - ElasticMike
 - FlapHearing
 - FloorFather
 - FurtivePowder
 - GabrielMilan
 - GarageGraph
 - GateCrack
 - HabitualHouses
 - HawaiiPandora
 - HourDebt
 - IncandescentIncrease
 - InterviewQuill
 - KevinMeter
 - LeafLamp
 - LiveRabbits
 - LogLeg
 - Mnemonics
 - Mnemonics
 - NumericNetwork
 - ObedientAttention
 - PaperPassenger
 - ParcelParty
 - ParchedPan
 - PeelPlant
 - PickPail
 - PlutoEpisode
 - PoisedCat
 - PonchoPotato
 - PorterPlough
 - PenguinZoo
 - QuicksandQuill
 - RapidSpy
 - RealizeProse
 - RefuseDigestion
 - RepresentativeProcess
 - RudeMist
 - SelectSlang
 - SkySquirrel
 - SlimyServant
 - SmartShop
 - SmashClock
 - SnobbishSoup
 - SpookySpace
 - StimulateSponge
 - StingSize
 - StoreSmile
 - SuggestSuit
 - TemporaryPan
 - TherapeuticTail
 - UnderIceberg
 - WaryWar
 - WaveWilderness
 - WildWire
 - WorthlessShow