---
- name: Set question and answer
  ansible.builtin.set_fact:
    question_name: "Change Directory Permissions"
    permissions: Add group write to the folder
    flag_token: Tosephtas

- name: Set MySQL statements
  ansible.builtin.set_fact:
    challenge: INSERT INTO challenges (name, description, max_attempts, value, category, type, state, requirements, connection_info, next_id) VALUES ("{{ question_name }}", "SSH to {{ linux_admin_ip }} port 22X where X is your user number with 'scr:password'{{NL2}}Folder\:/home/{{ ScrUser }}/PermMe{{NL2}}Give this folder {{ permissions }}{{NL2}}The flag will be stored in /home/{{ScrUser}}/challenges upon completion of the task.", 0, 5, "Linux", "standard", "visible", NULL, NULL, NULL)
    answer_flag: INSERT INTO flags (challenge_id, type, content, data) VALUES ((SELECT id FROM challenges WHERE name = "{{ question_name }}"), "static", "{{ flag_token }}", "case_insensitive")

- name: Put challenge into CTFd - Linux - Directory Permissions
  community.mysql.mysql_query:
    query: "{{ challenge }}"

- name: Put flag into CTFd - Linux - Directory Permissions
  community.mysql.mysql_query:
    query: "{{ answer_flag }}"