---
- name: Set question and answer
  ansible.builtin.set_fact:
    question_name: "String Decryption"
    decrypted: omnifariously
    encrypted: W+3+Klz8+oaqN8ms9sbrpw==
    type: AES256

- name: Set MySQL statements
  ansible.builtin.set_fact:
    challenge: INSERT INTO challenges (name, description, max_attempts, value, category, type, state, requirements, connection_info, next_id) VALUES ("{{ question_name }}", "Use {{ type }} to decrypt the following string{{NL2}}{{ encrypted }}{{NL2}}Make sure to use -pbkdf2' and '-nosalt'{{NL2}}Use to make the Key-> mysecretpassword", 0, 5, "Cryptography", "standard", "visible", NULL, NULL, NULL)
    answer_flag: INSERT INTO flags (challenge_id, type, content, data) VALUES ((SELECT id FROM challenges WHERE name = "{{ question_name }}"), "static", "{{ decrypted }}", "case_insensitive")

- name: Put challenge into CTFd - Decrypt
  community.mysql.mysql_query:
    query: "{{ challenge }}"

- name: Put flag into CTFd - Decrypt
  community.mysql.mysql_query:
    query: "{{ answer_flag }}"
